name: Run-Test-Action
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci    
      - name: Notify completion
        run: echo "Tests completed successfully!"
      - name: Run Tests
        run: npm test